on:
  issues:
    types: [opened, closed]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            consle.log(context.issue)
