on:
  issues:
    types: [opened, closed]

jobs:
  grant:
    if: ${{ github.event.issue.opened }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.teams.addOrUpdateMembershipForUserInOrg({
              org: context.organization.login,
              team_slug: "example-break-glass-CODEOWNERS",
              username: context.actor,
            })
  revoke:
    if: ${{ github.event.issue.closed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.teams.removeMembershipForUserInOrg({
              org: context.organization.login,
              team_slug: "example-break-glass-CODEOWNERS",
              username: context.actor,
            })
