on:
  issues:
    types: [opened, closed]

jobs:
  grant:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ SECRETS.BREAK_GLASS_TOKEN }}
          script: |
            const team = 'example-break-glass-CODEOWNERS'
            github.rest.teams.addOrUpdateMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: team,
              username: context.actor,
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Granted access: ${context.repo.owner}/${team}`
            })
  revoke:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ SECRETS.BREAK_GLASS_TOKEN }}
          script: |
            const team = 'example-break-glass-CODEOWNERS'
            github.rest.teams.removeMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: team,
              username: context.actor,
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Granted access: ${context.repo.owner}/${team}`
            })
