on:
  issues:
    types: [opened, closed]

jobs:
  grant:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    permissions:
      teams: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.teams.addOrUpdateMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: "example-break-glass-CODEOWNERS",
              username: context.actor,
            })
  revoke:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      teams: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.teams.removeMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: "example-break-glass-CODEOWNERS",
              username: context.actor,
            })
